spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create   # DDL ???? ??
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL57Dialect
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
